### ISSUE TITLE
Mali Mega Thread

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#11235]
### Issue

This is a collection of Mali issues for better tracking and overall understanding of the current status of it on yuzu.
Issues will be categorized into :

- Not booting
- Booting but crashing before main menu
- Booting with black-screen (audio going on ) 
- Booting with noticeable GFX issues.

Performance is not taken into consideration.
Each entry will contain all the details on the respective issue, with this just having the title and category of it.

Not booting 

- [ ] [Xenoblade Chronicles 2  ](https://github.com/yuzu-emu/yuzu/issues/11040)
- [ ] [Abzu](https://github.com/yuzu-emu/yuzu/issues/11039)

Booting with black-screen issues
- [ ] [Raji - UE4 Game](https://github.com/yuzu-emu/yuzu/issues/11178)
- [ ] [Mario and Rabbits: Sparks of Hope - UE4 Game](https://github.com/yuzu-emu/yuzu/issues/11020)

Booting but crashing before main menu 
- [ ] [Deaths Door](https://github.com/yuzu-emu/yuzu/issues/11038)
- [ ] [Mario and Rabbits: Sparks of Hope - UE4 Game](https://github.com/yuzu-emu/yuzu/issues/11020)

**Comment by Mobtoogood** [comment]
FIFA 22 booting up but freez later one on mali GPU

**Comment by Shadowsleeper** [comment]
Diablo 3 starts and is playable, but with fps at 16

**Comment by Chaostierobode** [comment]
Gnosia Black screen -> crash. The last know build to me on which it worked was 2921a4. I could play it on the max settings and still get consistent 60 fps. I have also opend an issue just type the game name for details.
